spring:
  application:
    name: ssia-ch06
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 1691
    url: jdbc:mysql://localhost:3306/security?useSSL=false&serverTimezone=UTC&autoReconnect=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
