version: '3'

services:
  database:
    container_name: app_data
    image: mysql:8
    environment:
      MYSQL_DATABASE: kwang
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - woowacourse-test-network

  application:
    container_name: main-server
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://woowacourse:3306/kwang
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"
    depends_on:
      - database
    networks:
      - woowacourse-test-network
    env_file:
      - .env

networks:
  woowacourse-test-network:
    driver: bridge